# Generated by Django 3.0.8 on 2022-04-28 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('transaction_amount', models.FloatField(max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.Transaction')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
